### ISSUE TITLE
Password option doesn't appear to be working

### ISSUE THREAD

**Issue by primalnick** [Vilagamer999/Bulk-Private-Vimeo-Downloader#2]
Using this format in the text file for a password protected video: https://vimeo.com/12345678::PASSWORD

Is getting this error in Terminal:
[vimeo] Extracting URL: https://vimeo.com/12345678
[vimeo] 12345678: Downloading webpage
ERROR: [vimeo] 12345678: This video is protected by a password, use the --video-password option

**Comment by ammar0466** [comment]
## Change video_password => videopassword
        # Include the video password if provided
        if password:
            ydl.params['video_password'] = password
        else:
            ydl.params.pop('video_password', None)

**Comment by ammar0466** [comment]
you can change setting to show verbose

yt_dlp_options = {
    ...
    "verbose": True,
    ...
}

**Comment by primalnick** [comment]
Thanks @ammar0466 ! Changing that fixed the password issue. 

Unfortunately, it's now throwing an error before it starts the download. It shows the destination of where the download will be, then just says ERROR. 

I turned on verbose, not sure if you can tell what's wrong from this at all:

ERROR: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3369, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/dash.py", line 56, in real_download
    return fd.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/external.py", line 50, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/external.py", line 294, in _call_downloader
    return super()._call_downloader(tmpfilename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/external.py", line 145, in _call_downloader
    cmd = [encodeArgument(a) for a in self._make_cmd(tmpfilename, info_dict)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/external.py", line 316, in _make_cmd
    cmd += self._configuration_args()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/external.py", line 129, in _configuration_args
    return _configuration_args(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 3539, in _configuration_args
    return cli_configuration_args(argdict, keys, default, use_compat)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/utils/_utils.py", line 3517, in cli_configuration_args
    assert isinstance(argdict, dict)
AssertionError

**Comment by ammar0466** [comment]
This because yt-dlp extractor setting
Try my fork on my github repo.
[https://github.com/ammar0466/Bulk-Private-Vimeo-Downloader/tree/main](url)

And also if downloaded content dont have sound you need to convert output to use AAC sound format.

**Comment by Vilagamer999** [comment]
Merged the fork, I'll try to test it out when I have the time 😄

**Comment by primalnick** [comment]
That worked @ammar0466 thanks!!
